# Page settings
baseurl = "/"
title = "KAPtivating"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "kaplaugher@kaptivating.io"
  # Navigation
  [params.navigation]
    brand = "KAPtivating Web Solutions"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Create a better web presence for your business"
    subtitle = 'Attract more customers, and make more money'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Submit your project and we will plan out the ideal engineering solution for you"
    url = "#fh5co-contact"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Let us code your projects with modern cloud based technology"
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Project Success will be reached through an agile and iterative development process"
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "We create modern, lightning fast websites"

    [[params.services.item]]
      title = "Website development using modern methodologies"
      description = "Modern sites need to be super fast and secure. The JAMStack is the new way to do this without breaking the bank"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Project Planning"
      description = "We will plan the technical aspects of your project in a clear and concise format. Then we will manage all the stages of the development process."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Strategic Design"
      description = "Your website won’t just look good—it’ll do good business, too. By strategically taking your website visitors on a constructed journey to your products and services, we can prime them for a purchase in a way that doesn’t make you feel salesy or sleazy in the slightest."
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "A CMS is a common requirement for any site to minimize the back and forth with developers and editors. We have experience with all the latest CMS technologies including JAMstack based cms’s"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About KAPtivating Web Solutions"
    description = "KAPtivating Web Solutions is your destination for world class software development. It’s no secret that almost all businesses need a web presence to compete in today’s digital age. This is especially true for new businesses, since having a fast, beautiful and efficient website is one of the most important business tools in helping them achieve their goals. Thats where we come in. We help businesses build a solid and positive web presence. We will plan and implement the best software development solution for your business and do whatever it takes to make sure we reach Project Success."


  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Contact us using the form below to set up your 100% free consultation. Let us help you reach your full potential."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Alpharetta, GA"],
        ["icon-envelope", "kaplaugher@kaptivating.io"],
        ["icon-globe", '<a href="https://kaptivating.io" target="_blank">KAPtivating.io</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; KAPtivating Web Solutions. All Rights Reserved.'
